export const products = [
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "short", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "jacket", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "dress", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "skirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "pant", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "short", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "Top", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "shirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "jacket", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "dress", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "skirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "pant", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "short", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "Top", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "shirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "jacket", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "dress", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "skirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "pant", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "short", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "Top", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "shirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "jacket", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "dress", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "skirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "pant", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "short", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "Top", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "shirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "jacket", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "dress", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "skirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "pant", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "short", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "Top", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "shirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "jacket", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "dress", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "skirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "pant", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "short", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "Top", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "shirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "jacket", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "dress", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "skirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "pant", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "short", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "Top", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "shirt", "", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Tops-and-shirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Dresses-and-skirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Tops-and-shirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Dresses-and-skirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Tops-and-shirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Dresses-and-skirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Tops-and-shirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Dresses-and-skirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Tops-and-shirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Dresses-and-skirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Tops-and-shirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Dresses-and-skirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Tops-and-shirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Dresses-and-skirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Tops-and-shirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Dresses-and-skirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Tops-and-shirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Dresses-and-skirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Tops-and-shirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Dresses-and-skirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Tops-and-shirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Pants-and-shorts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Dresses-and-skirts"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "",
        "before_price": "",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "",
        "before_price": "",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    },
    {
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "",
        "before_price": "",
        "current_price": "45.00",
        "colors": "blue black red",
        "sizes": "S M L",
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig", "Coats-and-jackets"]
    }
]