export const products = [
    {
        "productId" : "1",
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": ["blue", "black", "red"],
        "sizes": ["S", "M", "L"],
        "classify" : ["Women", "short", "", "popular-ig"]
    },
    {
        "productId" : "2",
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": ["blue", "black", "red"],
        "sizes": ["S", "M", "L"],
        "classify" : ["Women", "jacket", "", "popular-ig"]
    },
    {
        "productId" : "3",
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": ["blue", "black", "red"],
        "sizes": ["S", "M", "L"],
        "classify" : ["Women", "dress", "", "popular-ig"]
    },
    {
        "productId" : "4",
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": ["blue", "black", "red"],
        "sizes": ["S", "M", "L"],
        "classify" : ["Women", "skirt", "", "popular-ig"]
    },
    {
        "productId" : "5",
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": ["blue", "black", "red"],
        "sizes": ["S", "M", "L"],
        "classify" : ["Women", "pant", "", "popular-ig"]
    },
    {
        "productID" : "6",
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": ["blue", "black", "red"],
        "sizes": ["S", "M", "L"],
        "classify" : ["Women", "short", "", "popular-ig"]
    },
    {
        "productId" : "7",
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": ["blue", "black", "red"],
        "sizes": ["S", "M", "L"],
        "classify" : ["Women", "Top", "SpecialPrices", "popular-ig"]
    },
    {
        "productId" : "8",
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": ["blue", "black", "red"],
        "sizes": ["S", "M", "L"],
        "classify" : ["Women", "shirt", "SpecialPrices", "popular-ig"]
    },
    {
        "productId" : "9",
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": ["blue", "black", "red"],
        "sizes": ["S", "M", "L"],
        "classify" : ["Women", "coat", "SpecialPrices", "popular-ig"]
    },
    {
        "productId" : "10",
        "name": "zara-jean",
        "image": "pictures/display-products/zara-jeans.jpg",
        "image_hover": "pictures/display-products/male-model.jpg",
        "sales": "25%",
        "before_price": "62.00",
        "current_price": "45.00",
        "colors": ["blue", "black", "red"],
        "sizes": ["S", "M", "L"],
        "classify" : ["Women", "jacket", "SpecialPrices", "popular-ig"]
    }
]